### ISSUE TITLE
Support partial scoring features

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr3featsel#18]
This is the `k`  argument for praznik filters. If we had the filter hyperparameters `abs`, `perc` and `thres` available, we could do something smart with it.

**Comment by pat-s** [comment]
Blocked by #14.

This could give a little runtime decrease but I would not assume it to be really substantial. Before implementing it we should test which method (subsetting with `k` from `praznik` or subsetting in `mlr3featsel` after all scores have been calculated) is faster and then use only this one.

praznik filters are quite fast in general.
